//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enjoy.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enjoy.Core.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Signature&quot;:&quot;68e7129589a4ded6fc03702d3ee266f3bc443a12&quot;,&quot;TimeStamp&quot;:&quot;1532916008&quot;,&quot;Nonce&quot;:&quot;951808029&quot;,&quot;ReqMsg&quot;:&quot;&lt;xml&gt;\n    &lt;ToUserName&gt;&lt;![CDATA[gh_e0ee980c7e6e]]&gt;&lt;/ToUserName&gt;\n    &lt;Encrypt&gt;&lt;![CDATA[DjuDCoOlugk7eIYR20pFEPbc1kWUlHquKsDl6RzMlQ2NzN8xd67961ytd9/LzuzXVxJKfo7eTFOfIo9q/5SpOSMjzcuo3W5cVc+zC5aE+JNAdos7BDVRHwYQb2OUYk1oNfdk3vv1BVgP09HWAyZMryg3cAjjx4BQTNa//YIU/Bhfc7LdMc1oLpTQDZt57BNt1n0rqBHHJw/JD6cERLUpXXaU5gJ6rXxhDaom6SAT/W7ChEWAyH8teK0DFf2dQUjhkJxjwc4dxPW8tjPPVhi30kFVKGDhuvO0wZnW0rbWdCdq0ZEVhwOF9CbzRm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WeChatMsg {
            get {
                return ResourceManager.GetString("WeChatMsg", resourceCulture);
            }
        }
    }
}
